### ISSUE TITLE
What does corrupt_type: all_context do?

### ISSUE THREAD

**Issue by e0397123** [facebookresearch/online_dialog_eval#6]
May I know what is the difference between "all_context" with respect to "all" for the corrupt type option? I understand that "only semantics" and "only syntax" refer to training with only semantic negative samples and only syntactic negative samples respectively. What is the difference between the option "all_context" and "all"?

**Comment by koustuvsinha** [comment]
`all_context` was experimental and didn't add to the results of the paper. The idea was if we corrupt the context similarly as the responses, we might end up with a better Transition function that handles wrong/misaligned trajectories. I didn't find empirically any better performance with all_context - my hypothesis is that context might need a different kind of corruption schemes.

It can easily happen in a production setting where you can inadvertently inject bad/incoherent responses in your dialog context if the dialog model response is not that good, to begin with. This is a great future research direction if you are interested, happy to talk further about it! (drop me a mail if you end up exploring this direction!)
