### ISSUE TITLE
Issue running inference

### ISSUE THREAD

**Issue by dtuggener** [facebookresearch/online_dialog_eval#7]
I'm getting a `FileNotFoundError` when trying to run `sh run_inference.sh`:
`FileNotFoundError: [Errno 2] No such file or directory: '/private/home/koustuvs/mlp/latentDialogAnalysis/logs/log.txt'`
There seem to be some defaults in `args.py` that generate this path, but I can't seem to find where this particular error occurs.
The culprit call is https://github.com/facebookresearch/online_dialog_eval/blob/08bffd0760f4c07dd74ee6e483de276322bcff67/codes/inference.py#L176
which calls a LightningModule function, but I don't see where logs get involved there.

**Comment by koustuvsinha** [comment]
Thanks for posting this @dtuggener! I'll investigate this!

**Comment by koustuvsinha** [comment]
@dtuggener Thanks for bringing this issue, fixed this in the latest commit. Please let me know if you have any issues now on!

**Comment by dtuggener** [comment]
Great, the script now runs perfectly, thanks!
